Repository KHUMON-EDU/back-end, pull requests merged in 2023-10, with the labels that each got.

#4 feat: 의존성 설정 및 application 환경변수 분리
  build.gradle
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: :heavy_plus_sign: Dependency, ⚒️ Env

#6 feat: 도메인 패키지 생성 및 엔티티 구현
  src/main/java/com/teamh/khumon/KhumonApplication.java
  src/main/java/com/teamh/khumon/domain/LearningMaterial.java
  src/main/java/com/teamh/khumon/domain/MediaFileType.java
  src/main/java/com/teamh/khumon/domain/Member.java
  src/main/java/com/teamh/khumon/domain/Question.java
  src/main/java/com/teamh/khumon/domain/base/BaseEntity.java
Labels: ❗Important, ✨ New Feature

#8 feat: 리파지토리 인터페이스 생성
  src/main/java/com/teamh/khumon/repository/LearningMaterialRepository.java
  src/main/java/com/teamh/khumon/repository/MemberRepository.java
  src/main/java/com/teamh/khumon/repository/QuestionRepository.java
Labels: ❗Important

#12 feat: 컨트롤러, 서비스 패키지 생성
  src/main/java/com/teamh/khumon/controller/AuthenticationController.java
  src/main/java/com/teamh/khumon/service/AuthenticationService.java
Labels: ✨ New Feature

#15 feat: H2 데이터베이스를 사용하기 위한 스프링 시큐리티 구성
  build.gradle
  src/main/java/com/teamh/khumon/configuration/WebSecurityConfiguration.java
  src/main/java/com/teamh/khumon/repository/LearningMaterialRepository.java
Labels: :heavy_plus_sign: Dependency, ❗Important, ✨ New Feature, 🔒 Security, ⚒️ Env

#24 fix: redirect url 수정
  src/main/java/com/teamh/khumon/security/OAuth2LoginSuccessHandler.java
Labels: 🚨 Emergency

#26 hotfix: # 특수기호가 인코딩 되는 버그를 수정
  src/main/java/com/teamh/khumon/security/OAuth2LoginSuccessHandler.java
Labels: 🐛 Bug, 🚨 Emergency

#37 feat: 도커 컴포즈에 nginx를 접목한다.
  .github/workflows/gradle.yml
  .gitignore
  Dockerfile
  docker-compose.yml
  nginx/Dockerfile
  nginx/default.conf
Labels: ⚒️ Env

#43 feat: AI 서버와 rest 통신
  src/main/java/com/teamh/khumon/configuration/WebConfiguration.java
  src/main/java/com/teamh/khumon/configuration/WebSecurityConfiguration.java
  src/main/java/com/teamh/khumon/service/LearningMaterialService.java
  src/main/java/com/teamh/khumon/util/MediaUtil.java
Labels: ❗Important, ✨ New Feature, ⚒️ Env

#45 feat: ai 서버 응답 엔티티 영속화
  src/main/java/com/teamh/khumon/configuration/WebSecurityConfiguration.java
  src/main/java/com/teamh/khumon/domain/LearningMaterial.java
  src/main/java/com/teamh/khumon/domain/Question.java
  src/main/java/com/teamh/khumon/dto/AIResponse.java
  src/main/java/com/teamh/khumon/dto/Problem.java
  src/main/java/com/teamh/khumon/repository/AnswerRepository.java
  src/main/java/com/teamh/khumon/service/LearningMaterialService.java
  src/main/java/com/teamh/khumon/service/QuestionAnswerService.java
Labels: ❗Important, ✨ New Feature
